import {useEffect,useState} from 'react';import {useForm} from 'react-hook-form';import {useNavigate,useParams} from 'react-router-dom';import toast from 'react-hot-toast';import PageHeader from '../components/layout/PageHeader';import Input from '../components/common/Input';import Select from '../components/common/Select';import TextArea from '../components/common/TextArea';import Button from '../components/common/Button';
const unwrapRecord = (response) => {
  if (!response) return {};
  if (response.asset) return response.asset;
  if (response.data?.asset) return response.data.asset;
  if (response.data) return response.data;
  return response;
};
export default function ModuleFormPage({title,base,service,fields}){const {id}=useParams(),nav=useNavigate(),[remoteOptions,setRemoteOptions]=useState({});const {register,handleSubmit,reset,formState:{errors,isSubmitting}}=useForm();useEffect(()=>{if(id){service.getById(id).then(r=>{const rec=unwrapRecord(r);if(title==='Asset'){if(rec.category&&typeof rec.category==='object')rec.category=rec.category._id;if(rec.department&&typeof rec.department==='object')rec.department=rec.department._id;}reset(rec)}).catch(()=>reset({}))}},[id,service,reset,title]);useEffect(()=>{fields.filter(f=>f.loadOptions).forEach(f=>f.loadOptions().then(options=>setRemoteOptions(current=>({...current,[f.name]:options}))).catch(()=>toast.error(`Could not load ${f.label.toLowerCase()} options`)))},[fields]);const submit=async d=>{const payload={...d};if (title === 'Asset') {const categoryValue=payload.category; if (categoryValue && typeof categoryValue === 'string' && !categoryValue.match(/^[0-9a-fA-F]{24}$/)) { const matchedOption=(remoteOptions.category||[]).find((option)=>option.value===categoryValue||option.label===categoryValue); payload.category = matchedOption?.value || categoryValue; } const departmentValue=payload.department; if (departmentValue && typeof departmentValue === 'string' && !departmentValue.match(/^[0-9a-fA-F]{24}$/)) { const matchedOption=(remoteOptions.department||[]).find((option)=>option.value===departmentValue||option.label===departmentValue); payload.department = matchedOption?.value || departmentValue; }}try{id?await service.update(id,payload):await service.create(payload);toast.success(`${title} saved successfully`);nav(base)}catch(error){toast.error(error?.response?.data?.message || 'Could not save changes')}};return <><PageHeader title={`${id?'Edit':'Add'} ${title}`} description="Fields marked with an asterisk are required."/><form onSubmit={handleSubmit(submit)} className="card max-w-4xl"><div className="grid gap-5 md:grid-cols-2">{fields.map(f=>{const p={...register(f.name,{required:f.required&&`${f.label} is required`,pattern:f.pattern}),label:f.label,required:f.required,error:errors[f.name],placeholder:f.placeholder};if(f.type==='select')return <Select key={f.name} {...p} options={remoteOptions[f.name]||f.options}/>;if(f.type==='textarea')return <div className="md:col-span-2" key={f.name}><TextArea {...p}/></div>;return <Input key={f.name} {...p} type={f.type||'text'}/>})}</div><div className="mt-7 flex justify-end gap-3 border-t pt-5"><button type="button" onClick={()=>nav(base)} className="btn-secondary">Cancel</button><Button loading={isSubmitting}>Save {title}</Button></div></form></>}
